# -*- mode: ruby -*-

# vi: set ft=ruby :

Vagrant.configure("2") do |config|

# Box utilizada pelas duas máquinas.

# Ubuntu Server 22.04 (Jammy).

config.vm.box = "ubuntu/jammy64"

# ==========================================================

# VM 1 - JENKINS

# ==========================================================

config.vm.define "jenkins" do |jenkins|


# Define o hostname da máquina.
jenkins.vm.hostname = "jenkins"

# Define um IP privado exclusivo para a VM.
jenkins.vm.network "private_network", ip: "192.168.56.10"

# Configurações do VirtualBox.
# 1024 MB de memória e 2 CPUs.
jenkins.vm.provider "virtualbox" do |vb|
  vb.memory = 1024
  vb.cpus = 2
end

# Executa o script responsável pela configuração do Jenkins
# e das demais ferramentas necessárias nesta máquina.
jenkins.vm.provision "shell", path: "scripts/jenkins.sh"


end

# ==========================================================

# VM 2 - PRODUÇÃO

# ==========================================================

config.vm.define "prod" do |prod|


# Define o hostname da máquina.
prod.vm.hostname = "prod"

# Define um IP privado diferente do utilizado pelo Jenkins.
prod.vm.network "private_network", ip: "192.168.56.20"

# Configurações do VirtualBox.
# 1024 MB de memória e 2 CPUs.
prod.vm.provider "virtualbox" do |vb|
  vb.memory = 1024
  vb.cpus = 2
end

# Executa o script responsável pela instalação do Node.js
# e configuração do ambiente de produção.
prod.vm.provision "shell", path: "scripts/nodejs.sh"

# ========================================================
# EXTRA - PASTA COMPARTILHADA
# ========================================================
# Compartilha a pasta do projeto com a VM de produção.
# Isso permite testar o aplicativo diretamente dentro da VM.
#
# A pasta atual do projeto será montada em /var/www/app.
prod.vm.synced_folder ".", "/var/www/app"


end

end
